### ISSUE TITLE
Load Asset Once

### ISSUE THREAD

**Issue by acarlstein** [bertramdev/grails-asset-pipeline#370]
This is not an actual issue. It is a "would be nice" feature.

It would be wonderful if there could be a flag to indicate that the asset should be loaded once. In this way, we can prevent multiple injection of assets into the page(s) when such assets are already there.

One way could be implementing a solution like in C++ with the diamond problem. In C++, we can use the pre-processor to indicate that we only wish to include a class once. If an specific variable doesn't exist, create such variable and include the content, else do not include the content because its already there.

**Comment by davydotcom** [comment]
It already does this unless you are incorrectly using the asset tag to add
page js and css instead of the directives and manifest

**Comment by kdpeders** [comment]
I agree this does not appear to do this currently, and I think this might be a bug because it seems to fundamentally break how plugins using asset pipeline should work.  Because of this issue, they cannot contain assets that could have overlapping dependencies with the applications using them (e.g. JQuery)

Here is an example:  A plugin provides an asset manifest `myplugin.js` that is required internally in one of the plugins GSPs.

**myplugin.js**
```
//= require jquery
//= require myLocalFile
```

**myplugin.gsp**
```
<head>
  <asset:javascript src=" myplugin.js" />
</head>
```

Then in the Application using the plugin (and JQuery)

**application.js**
```
//= require jquery
//= require myApplicationFile
```

**main.gsp** (application Sitemesh Template wrapping the `myplugin.gsp` page) 
```
<head>
  <asset:javascript src=" application.js" />
</head>
```

If the application includes the plugins GSP then the result is including JQuery twice on the page (which is not correct).

**Comment by davydotcom** [comment]
not a bug this is by design and how the assets are digested and bundled and are performant without having to rebundle per gsp file

**Comment by davydotcom** [comment]
do not include the same file twice in a gsp. if you use the root `application.js` or `application.css` to build your final package your good to go

**Comment by davydotcom** [comment]
if you need to package shared assets for other views as a plugin you can place them in a assets subfolder by plugin name like `assets/javascripts/plugina/test.js` then instruct your users to add this line to `application.js`

```
//= require_full_tree plugina
```
